name: CI/CD for React App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  # Trigger workflow on tag creation
  create:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      # - name: Test
      #   run: npm test -- --coverage

      - name: Update package.json version
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          echo "Updating package.json version..."
          npm version patch --no-git-tag-version

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
