name: Deploy and Tag Release

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build_and_deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: update_version  # Wait for update_version job to complete
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          publish_branch: gh-pages
    
  update_version:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update Version in package.json
        id: update_version
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          new_version=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          npm version $new_version --no-git-tag-version
          echo "Updated version to $new_version in package.json"
          echo "new_version=${new_version}" >> $GITHUB_ENV

      - name: Commit Version Change
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add package.json
          git commit -m "Update version to ${new_version}"
          git push origin HEAD:main
