name: Deploy and Tag Release

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build_and_deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./.next

  update_version:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update Version in package.json
        id: update_version
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          new_version=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          npm version $new_version --no-git-tag-version
          echo "Updated version to $new_version in package.json"
          echo "new_version=${new_version}" >> $GITHUB_ENV

      - name: Commit Version Change
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add package.json
          git commit -m "Update version to ${new_version}"
          git push origin HEAD:main

  build_after_update_version:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs: update_version
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Reset Git working directory
        run: git reset --hard

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Setup Pages
        uses: actions/configure-pages@v5
        with:
          # Automatically inject basePath in your Next.js configuration file and disable
          # server side image optimization (https://nextjs.org/docs/api-reference/next/image#unoptimized).
          #
          # You may remove this line if you want to manage the configuration yourself.
          static_site_generator: next

      - name: Install dependencies
        run: npm install

      - name: Create .env file
        run: |
          echo "NEXT_PUBLIC_API_URL=${{ secrets.PRODUCTION_API_URL }}" > .env
          echo "NEXT_PUBLIC_SECRET_KEY=${{ secrets.PRODUCTION_SECRET_KEY }}" >> .env

      - name: Build with Next.js
        run: ${{ steps.detect-package-manager.outputs.runner }} next build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    name: Deploy to Production
    if: startsWith(github.ref, 'refs/tags/')
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build_after_update_version
    steps:
      - name: Deploy to Production
        id: deployment
        uses: actions/deploy-pages@v4