name: Deploy to Staging and Production

on:
  push:
    branches:
      - main
    tags:
      - "*"

jobs:
  deploy_staging:
    name: Deploy to Staging
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Set environment variables from .env.staging
        run: |
          echo "API_URL=${{ secrets.STAGING_API_URL }}" >> .env
          echo "SECRET_KEY=${{ secrets.STAGING_SECRET_KEY }}" >> .env

      - name: Build for Staging
        run: npm run build:staging

      - name: Deploy to Staging
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./.next

  deploy_production:
    name: Deploy to Production
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Set environment variables from .env.production
        run: |
          echo "API_URL=${{ secrets.PRODUCTION_API_URL }}" >> .env
          echo "SECRET_KEY=${{ secrets.PRODUCT_SECRET_KEY }}" >> .env

      - name: Build for Production
        run: npm run build:production

      - name: Deploy to Production
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./.next
