name: Deploy and Tag Release

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          publish_branch: gh-pages

      - name: Set up Git
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Create Release Tag
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          tag=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          git tag "${tag}" -m "Release ${tag}"
          git push origin "${tag}"
